"use client";

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'tr';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
    en: {
        "nav.dashboard": "Dashboard",
        "nav.pipeline": "Pipeline",
        "nav.deals": "Deals",
        "nav.brands": "Brands",
        "nav.influencers": "Influencers",
        "nav.contacts": "Contacts",
        "nav.calendar": "Calendar",
        "nav.finance": "Finance",
        "nav.leaderboard": "Leaderboard",
        "nav.automations": "Automations",
        "nav.discovery": "Discovery",
        "nav.analytics": "AI Analytics",
        "nav.settings": "Settings",
        "nav.logout": "Logout",
        "dashboard.welcome": "Welcome back",
        "dashboard.monthly_revenue": "Monthly Revenue",
        "dashboard.active_pipeline": "Active Pipeline",
        "dashboard.win_rate": "Win Rate",
        "dashboard.executive_review": "Executive Review",
        "dashboard.view_all_deals": "View all deals closing this month",
        "dashboard.view_finance": "View finance report",
        "finance.title": "Finance & Overview",
        "finance.subtitle": "Track your earnings, overdue payments, and expected commissions.",
        "finance.tab_overview": "Overview",
        "finance.tab_commissions": "Commissions Engine",
        "finance.total_expected": "Total Expected",
        "finance.total_collected": "Total Collected",
        "finance.overdue_risk": "Overdue / Risk",
        "finance.monthly_revenue": "Monthly Revenue",
        "finance.top_brands": "🏆 Top Paying Brands",
        "finance.scheduled_payments": "All Scheduled Payments",
        "finance.commission_breakdown": "Commission Breakdown",
        "finance.sales_rep_commissions": "Total Sales Rep Commissions",
        "finance.influencer_commissions": "Total Influencer Commissions",
        "leaderboard.title": "Leaderboard & Performance",
        "leaderboard.subtitle": "Track the LTV and performance scores of your network.",
        "pipeline.title": "Sales Pipeline",
        "pipeline.subtitle": "Manage and track deals through their lifecycle.",
        "common.create": "Create",
        "common.cancel": "Cancel",
        "common.save": "Save",
        "common.edit": "Edit",
        "common.delete": "Delete",
        "common.search": "Search...",
        "brands.title": "Brands & Clients",
        "brands.subtitle": "Manage your brand relationships and company profiles.",
        "brands.new_brand": "New Brand",
        "influencers.title": "Influencer Database",
        "influencers.subtitle": "Manage your influencer network, discovery, and pricing.",
        "influencers.new_influencer": "New Influencer",
        "influencers.label_platform": "Platform",
        "influencers.label_followers": "Followers",
        "influencers.label_category": "Category",
        "influencers.label_price": "Price per Post",
        "influencers.label_engagement": "Engagement Rate",
        "influencers.no_influencers": "No influencers found. Start building your database!",
        "contacts.title": "Contacts & People",
        "contacts.subtitle": "Manage external stakeholders, influencers, and brand reps.",
        "contacts.new_contact": "New Contact",
        "deals.title": "Deals & Contracts",
        "deals.subtitle": "View and manage all active contracts and documents.",
        "deals.new_deal": "New Deal",
        "deals.ai_autofill": "AI Contract Autofill",
        "calendar.title": "Calendar & Events",
        "calendar.subtitle": "Manage deal schedules, meetings, and important dates.",
        "calendar.tasks": "Tasks",
        "calendar.tasks_desc": "Manage your personal to-do list for this day.",
        "automations.title": "Automations & Hooks",
        "automations.subtitle": "Configure AI hooks, email sequences, and background tasks.",
        "automations.new_rule": "New Rule",
        "automations.create_rule_title": "Create Automation Rule",
        "automations.create_rule_desc": "Define what triggers the automation and what action happens.",
        "automations.rule_name": "Rule Name",
        "automations.description": "Description (Optional)",
        "automations.trigger": "When this happens (Trigger)",
        "automations.action": "Do this (Action)",
        "automations.saving": "Saving...",
        "automations.create_btn": "Create Rule",
        "automations.status_active": "Active",
        "automations.status_paused": "Paused",
        "automations.pause_rule": "Pause Rule",
        "automations.activate_rule": "Activate Rule",
        "automations.label_trigger": "Trigger",
        "automations.label_action": "Action",
        "automations.no_automations": "No automations yet",
        "automations.no_automations_desc": "Create rules to automate repetitive tasks and let the CRM do the heavy lifting for your agency.",
        "automations.create_first": "Create your first rule",
        "automations.trigger.deal_stage_changed": "Deal Stage Changed",
        "automations.trigger.deliverable_status_changed": "Deliverable Status Changed (Coming Soon)",
        "automations.action.send_email": "Send Automated Email",
        "automations.action.send_slack": "Send Slack Message",
        "settings.title": "Settings",
        "settings.subtitle": "Manage your agency profile, preferences, and account security.",
        "settings.personal_profile": "Personal Profile",
        "settings.personal_profile_desc": "Update your photo and personal details.",
        "settings.your_name": "Your Name",
        "settings.email_address": "Email Address",
        "settings.agency_workspace": "Agency / Workspace",
        "settings.agency_name": "Agency Name",
        "settings.save_profile": "Save Profile Changes",
        "settings.security_passwords": "Security & Passwords",
        "settings.security_passwords_desc": "Ensure your account remains safe.",
        "settings.current_password": "Current Password",
        "settings.new_password": "New Password",
        "settings.update_password": "Update Password",
        "settings.preferences": "Preferences",
        "settings.dark_mode": "Dark Mode",
        "settings.dark_mode_desc": "Toggle site theme.",
        "settings.saving": "Saving...",
        "settings.success_profile": "Profile updated successfully!",
        "settings.error_profile": "Failed to update profile.",
        "settings.success_password": "Password changed successfully!",
        "settings.error_password": "Failed to update password.",
        "settings.dark_mode_active": "Dark Mode activated & saved",
        "settings.light_mode_active": "Light Mode activated",
        "billing.title": "Billing & Subscription",
        "billing.subtitle": "Manage your pricing plan, users, and invoices.",
        "dashboard.monthly_revenue_sub": "Total revenue collected this month",
        "dashboard.active_pipeline_sub": "Across {count} active deals",
        "dashboard.win_rate_sub": "Percentage of won deals",
        "dashboard.overdue_payments": "Overdue Payments",
        "dashboard.overdue_payments_sub": "Across {count} invoices",
        "dashboard.todays_tasks": "Today's Tasks",
        "dashboard.deliverables_due": "Deliverables Due",
        "dashboard.payments_due": "Payments Due",
        "dashboard.weekly_overview": "Weekly Deliverables Overview",
        "dashboard.deliverables_due_today": "Deliverables Due Today",
        "dashboard.total_deals": "Total Deals",
        "dashboard.pipeline_overview": "Pipeline Overview",
        "dashboard.recent_activity": "Recent Activity",
        "dashboard.no_pipeline_data": "No pipeline data available.",
        "dashboard.no_recent_activity": "No recent activity.",
        "common.title": "Title",
        "common.brand": "Brand",
        "common.stage": "Stage",
        "common.value": "Value",
        "common.platform": "Platform",
        "common.actions": "Actions",
        "common.loading": "Loading...",
        "deals.no_deals": "No deals found. Create one from the Pipeline page!",
        "deals.view_details": "View Details",
        "deals.delete_deal": "Delete Deal",
        "deals.details_title": "Deal Details",
        "deals.created_at": "Created At",
        "deals.contact_person": "Contact Person",
        "deals.ai_score": "AI Deal Prediction Score",
        "deals.notes": "Notes",
        "deals.no_notes": "No notes added for this deal.",
        "stage.LEAD": "Lead",
        "stage.NEGOTIATION": "Negotiation",
        "stage.APPROVED": "Approved",
        "stage.COMPLETED": "Completed",
        "brands.brand_name": "Brand Name",
        "brands.website": "Website",
        "brands.contacts": "Contacts",
        "brands.deals": "Deals",
        "brands.view_profile": "View Profile",
        "brands.delete_brand": "Delete Brand",
        "brands.label_name": "Brand Name",
        "brands.label_website": "Website (Optional)",
        "brands.label_notes": "Notes (Optional)",
        "brands.submit_save": "Save Brand",
        "brands.no_brands": "No brands found. Add your first brand to get started!",
        "contacts.total_contacts": "Total Contacts",
        "contacts.active_brands": "Active Brands",
        "contacts.network_health": "Network Health",
        "contacts.fully_connected": "Fully Connected",
        "contacts.directory": "Contact Directory",
        "contacts.info": "Contact Info",
        "contacts.position": "Position",
        "contacts.no_contacts": "No contacts found.",
        "contacts.no_brand": "No Brand",
        "contacts.delete_confirm": "Are you sure you want to remove this contact?",
        "contacts.add_new": "Add New Contact",
        "contacts.label_name": "Full Name",
        "contacts.label_email": "Email",
        "contacts.label_phone": "Phone",
        "contacts.submit_add": "Add Contact",
        "finance.earned_this_month": "Earned this month",
        "finance.needs_attention": "Needs immediate attention",
        "finance.scheduled_payments_sub": "View and manage all your incoming transactions.",
        "finance.table_project": "Project / Deal",
        "finance.table_amount": "Amount",
        "finance.table_status": "Status",
        "finance.table_due_date": "Due Date",
        "finance.no_payments": "No payments recorded yet.",
        "finance.status_paid": "Paid",
        "finance.status_pending": "Pending",
        "finance.status_overdue": "Overdue",
        "finance.action_mark_paid": "Mark as Paid",
        "finance.action_mark_pending": "Mark as Pending",
        "finance.commission_breakdown_sub": "Detailed list of commissions per completed deal.",
        "finance.table_deal_brand": "Deal & Brand",
        "finance.table_deal_value": "Total Deal Value (TRY)",
        "finance.table_sales_rep": "Sales Rep",
        "finance.table_influencer": "Influencer",
        "leaderboard.trust_score": "Trust Score",
        "leaderboard.total_revenue": "Total Revenue",
        "leaderboard.ontime_rate": "On-Time Rate",
        "leaderboard.table_rank": "Rank",
        "leaderboard.table_influencer": "Influencer",
        "leaderboard.table_score": "Score",
        "leaderboard.table_ltv": "Lifetime Value (LTV)",
        "leaderboard.table_ontime": "On-Time Delivery",
        "leaderboard.table_active_deals": "Active Deals",
        "leaderboard.no_data": "No data yet",
        "leaderboard.no_data_desc": "Start closing deals and adding deliverables to build your leaderboard."
    },
    tr: {
        "nav.dashboard": "Ana Ekran",
        "nav.pipeline": "İş Akışı",
        "nav.deals": "Fırsatlar",
        "nav.brands": "Markalar",
        "nav.influencers": "İçerik Üreticileri",
        "nav.contacts": "Kişiler",
        "nav.calendar": "Takvim",
        "nav.finance": "Finans",
        "nav.leaderboard": "Liderlik Tablosu",
        "nav.automations": "Otomasyonlar",
        "nav.discovery": "Keşfet",
        "nav.analytics": "AI Analiz",
        "nav.settings": "Ayarlar",
        "nav.logout": "Çıkış Yap",
        "dashboard.welcome": "Tekrar Hoşgeldin",
        "dashboard.monthly_revenue": "Aylık Ciro",
        "dashboard.active_pipeline": "Aktif Fırsat Değeri",
        "dashboard.win_rate": "Kazanma Oranı",
        "dashboard.executive_review": "Patron Paneli",
        "dashboard.view_all_deals": "Bu ay kapanacak olanları gör",
        "dashboard.view_finance": "Finansal rapora git",
        "finance.title": "Finans ve Özet",
        "finance.subtitle": "Kazançları, gecikmiş ödemeleri ve beklenen primleri takip edin.",
        "finance.tab_overview": "Genel Bakış",
        "finance.tab_commissions": "Komisyon Motoru",
        "finance.total_expected": "Beklenen Toplam",
        "finance.total_collected": "Tahsil Edilen Toplam",
        "finance.overdue_risk": "Gecikmiş / Riskli",
        "finance.monthly_revenue": "Aylık Ciro",
        "finance.top_brands": "🏆 En Çok Kazandıran Markalar",
        "finance.scheduled_payments": "Tüm Planlı Ödemeler",
        "finance.commission_breakdown": "Komisyon Dağılımı",
        "finance.sales_rep_commissions": "Toplam Satışçı Primleri",
        "finance.influencer_commissions": "Toplam İçerik Üretici Primleri",
        "leaderboard.title": "Liderlik Tablosu ve Performans",
        "leaderboard.subtitle": "Ağınızın LTV ve performans puanlarını takip edin.",
        "pipeline.title": "Satış Süreci",
        "pipeline.subtitle": "Fırsatları yaşam döngüleri boyunca yönetin ve takip edin.",
        "common.create": "Oluştur",
        "common.cancel": "İptal",
        "common.save": "Kaydet",
        "common.edit": "Düzenle",
        "common.delete": "Sil",
        "common.search": "Ara...",
        "brands.title": "Markalar ve Müşteriler",
        "brands.subtitle": "Marka ilişkilerini ve şirket profillerini yönetin.",
        "brands.new_brand": "Yeni Marka",
        "influencers.title": "Influencer Veritabanı",
        "influencers.subtitle": "Influencer ağınızı, keşif sürecini ve fiyatlandırmayı yönetin.",
        "influencers.new_influencer": "Yeni Influencer",
        "influencers.label_platform": "Platform",
        "influencers.label_followers": "Takipçi Sayısı",
        "influencers.label_category": "Kategori",
        "influencers.label_price": "Post Başı Ücret",
        "influencers.label_engagement": "Etkileşim Oranı",
        "influencers.no_influencers": "Influencer bulunamadı. Veritabanınızı oluşturmaya başlayın!",
        "contacts.title": "Kişiler ve Temsilciler",
        "contacts.subtitle": "Dış paydaşları, içerik üreticilerini ve marka temsilcilerini yönetin.",
        "contacts.new_contact": "Yeni Kişi",
        "deals.title": "Sözleşmeler ve Fırsatlar",
        "deals.subtitle": "Tüm aktif sözleşmeleri ve belgeleri görüntüleyin ve yönetin.",
        "deals.new_deal": "Yeni Fırsat",
        "deals.ai_autofill": "Yapay Zeka Sözleşme Doldurma",
        "calendar.title": "Takvim ve Etkinlikler",
        "calendar.subtitle": "Fırsat programlarını, toplantıları ve önemli tarihleri yönetin.",
        "calendar.tasks": "Görevler",
        "calendar.tasks_desc": "Bu gün için kişisel yapılacaklar listenizi yönetin.",
        "automations.title": "Otomasyonlar ve Kancalar",
        "automations.subtitle": "Yapay zeka kancalarını, e-posta sıralarını ve arka plan görevlerini yapılandırın.",
        "automations.new_rule": "Yeni Kural",
        "automations.create_rule_title": "Otomasyon Kuralı Oluştur",
        "automations.create_rule_desc": "Otomasyonu neyin tetikleyeceğini ve hangi eylemin gerçekleşeceğini belirleyin.",
        "automations.rule_name": "Kural Adı",
        "automations.description": "Açıklama (Opsiyonel)",
        "automations.trigger": "Bu olduğunda (Tetikleyici)",
        "automations.action": "Bunu yap (Eylem)",
        "automations.saving": "Kaydediliyor...",
        "automations.create_btn": "Kural Oluştur",
        "automations.status_active": "Aktif",
        "automations.status_paused": "Duraklatıldı",
        "automations.pause_rule": "Kuralı Duraklat",
        "automations.activate_rule": "Kuralı Aktifleştir",
        "automations.label_trigger": "Tetikleyici",
        "automations.label_action": "Eylem",
        "automations.no_automations": "Henüz otomasyon yok",
        "automations.no_automations_desc": "Tekrarlayan görevleri otomatikleştirmek için kurallar oluşturun ve CRM'in sizin için çalışmasına izin verin.",
        "automations.create_first": "İlk kuralınızı oluşturun",
        "automations.trigger.deal_stage_changed": "Fırsat Aşaması Değişti",
        "automations.trigger.deliverable_status_changed": "Teslimat Durumu Değişti (Yakında)",
        "automations.action.send_email": "Otomatik E-posta Gönder",
        "automations.action.send_slack": "Slack Mesajı Gönder",
        "settings.title": "Ayarlar",
        "settings.subtitle": "Ajans profilinizi, tercihlerinizi ve hesap güvenliğinizi yönetin.",
        "settings.personal_profile": "Kişisel Profil",
        "settings.personal_profile_desc": "Fotoğrafınızı ve kişisel bilgilerinizi güncelleyin.",
        "settings.your_name": "Adınız",
        "settings.email_address": "E-posta Adresi",
        "settings.agency_workspace": "Ajans / Çalışma Alanı",
        "settings.agency_name": "Ajans Adı",
        "settings.save_profile": "Profil Değişikliklerini Kaydet",
        "settings.security_passwords": "Güvenlik ve Şifreler",
        "settings.security_passwords_desc": "Hesabınızın güvende kalmasını sağlayın.",
        "settings.current_password": "Mevcut Şifre",
        "settings.new_password": "Yeni Şifre",
        "settings.update_password": "Şifreyi Güncelle",
        "settings.preferences": "Tercihler",
        "settings.dark_mode": "Karanlık Mod",
        "settings.dark_mode_desc": "Site temasını değiştirin.",
        "settings.saving": "Kaydediliyor...",
        "settings.success_profile": "Profil başarıyla güncellendi!",
        "settings.error_profile": "Profil güncellenemedi.",
        "settings.success_password": "Şifre başarıyla değiştirildi!",
        "settings.error_password": "Şifre güncellenemedi.",
        "settings.dark_mode_active": "Karanlık Mod aktifleştirildi ve kaydedildi",
        "settings.light_mode_active": "Aydınlık Mod aktifleştirildi",
        "billing.title": "Abonelik ve Faturalama",
        "billing.subtitle": "Fiyatlandırma planınızı, kullanıcılarınızı ve faturalarınızı yönetin.",
        "dashboard.monthly_revenue_sub": "Bu ay toplanan toplam gelir",
        "dashboard.active_pipeline_sub": "{count} aktif fırsat üzerinden",
        "dashboard.win_rate_sub": "Kazanılan fırsatların yüzdesi",
        "dashboard.overdue_payments": "Gecikmiş Ödemeler",
        "dashboard.overdue_payments_sub": "{count} fatura üzerinden",
        "dashboard.todays_tasks": "Bugünün Görevleri",
        "dashboard.deliverables_due": "Teslim Edilecekler",
        "dashboard.payments_due": "Bekleyen Ödemeler",
        "dashboard.weekly_overview": "Haftalık Teslimat Özeti",
        "dashboard.deliverables_due_today": "Bugün Teslim Edilecekler",
        "dashboard.total_deals": "Toplam Fırsat",
        "dashboard.pipeline_overview": "Satış Süreci Özeti",
        "dashboard.recent_activity": "Son Hareketler",
        "dashboard.no_pipeline_data": "Satış süreci verisi bulunamadı.",
        "dashboard.no_recent_activity": "Son hareket bulunamadı.",
        "common.title": "Başlık",
        "common.brand": "Marka",
        "common.stage": "Aşama",
        "common.value": "Tutar",
        "common.platform": "Platform",
        "common.actions": "İşlemler",
        "common.loading": "Yükleniyor...",
        "deals.no_deals": "Fırsat bulunamadı. Satış Süreci sayfasından yeni bir fırsat oluşturun!",
        "deals.view_details": "Detayları Görüntüle",
        "deals.delete_deal": "Fırsatı Sil",
        "deals.details_title": "Fırsat Detayları",
        "deals.created_at": "Oluşturulma Tarihi",
        "deals.contact_person": "İlgili Kişi",
        "deals.ai_score": "Yapay Zeka Başarı Tahmini",
        "deals.notes": "Notlar",
        "deals.no_notes": "Bu fırsat için not eklenmemiş.",
        "stage.LEAD": "Aday (Lead)",
        "stage.NEGOTIATION": "Görüşme",
        "stage.APPROVED": "Onaylandı",
        "stage.COMPLETED": "Tamamlandı",
        "brands.brand_name": "Marka Adı",
        "brands.website": "Web Sitesi",
        "brands.contacts": "Kişiler",
        "brands.deals": "Fırsatlar",
        "brands.view_profile": "Profili Görüntüle",
        "brands.delete_brand": "Markayı Sil",
        "brands.label_name": "Marka Adı",
        "brands.label_website": "Web Sitesi (Opsiyonel)",
        "brands.label_notes": "Notlar (Opsiyonel)",
        "brands.submit_save": "Markayı Kaydet",
        "brands.no_brands": "Marka bulunamadı. Başlamak için ilk markanızı ekleyin!",
        "contacts.total_contacts": "Toplam Kişi",
        "contacts.active_brands": "Aktif Markalar",
        "contacts.network_health": "Ağ Sağlığı",
        "contacts.fully_connected": "Tamamen Bağlı",
        "contacts.directory": "Kişi Rehberi",
        "contacts.info": "İletişim Bilgileri",
        "contacts.position": "Pozisyon",
        "contacts.no_contacts": "Kişi bulunamadı.",
        "contacts.no_brand": "Marka Yok",
        "contacts.delete_confirm": "Bu kişiyi silmek istediğinize emin misiniz?",
        "contacts.add_new": "Yeni Kişi Ekle",
        "contacts.label_name": "Ad Soyad",
        "contacts.label_email": "E-posta",
        "contacts.label_phone": "Telefon",
        "contacts.submit_add": "Kişiyi Ekle",
        "finance.earned_this_month": "Bu ay kazanılan",
        "finance.needs_attention": "Acil ilgilenilmesi gerekiyor",
        "finance.scheduled_payments_sub": "Tüm gelen işlemlerinizi görüntüleyin ve yönetin.",
        "finance.table_project": "Proje / Fırsat",
        "finance.table_amount": "Tutar",
        "finance.table_status": "Durum",
        "finance.table_due_date": "Son Ödeme Tarihi",
        "finance.no_payments": "Henüz ödeme kaydedilmemiş.",
        "finance.status_paid": "Ödendi",
        "finance.status_pending": "Bekliyor",
        "finance.status_overdue": "Gecikmiş",
        "finance.action_mark_paid": "Ödendi Olarak İşaretle",
        "finance.action_mark_pending": "Bekliyor Olarak İşaretle",
        "finance.commission_breakdown_sub": "Tamamlanmış fırsat başına detaylı komisyon listesi.",
        "finance.table_deal_brand": "Fırsat & Marka",
        "finance.table_deal_value": "Toplam Fırsat Değeri (TRY)",
        "finance.table_sales_rep": "Satış Temsilcisi",
        "finance.table_influencer": "İçerik Üreticisi",
        "leaderboard.trust_score": "Güven Puanı",
        "leaderboard.total_revenue": "Toplam Gelir",
        "leaderboard.ontime_rate": "Zamanında Teslim Oranı",
        "leaderboard.table_rank": "Sıralama",
        "leaderboard.table_influencer": "İçerik Üreticisi",
        "leaderboard.table_score": "Puan",
        "leaderboard.table_ltv": "Yaşam Boyu Değer (LTV)",
        "leaderboard.table_ontime": "Zamanında Teslim",
        "leaderboard.table_active_deals": "Aktif Fırsatlar",
        "leaderboard.no_data": "Henüz veri yok",
        "leaderboard.no_data_desc": "Liderlik tablonuzu oluşturmak için fırsatları kapatın ve teslimatlar ekleyin."
    }
};

const LanguageContext = createContext<LanguageContextType>({
    language: 'en',
    setLanguage: () => { },
    t: (key: string) => key,
});

export const useLanguage = () => useContext(LanguageContext);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguageState] = useState<Language>('en');

    useEffect(() => {
        const savedLang = localStorage.getItem('inf_crm_lang') as Language;
        if (savedLang && (savedLang === 'en' || savedLang === 'tr')) {
            setLanguageState(savedLang);
        } else {
            // Check browser language
            const browserLang = navigator.language.startsWith('tr') ? 'tr' : 'en';
            setLanguageState(browserLang);
        }
    }, []);

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
        localStorage.setItem('inf_crm_lang', lang);
    };

    const t = (key: string): string => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}
